### ISSUE TITLE
Bug on rtl documentation

### ISSUE THREAD

**Issue by HamedMasafi** [prrashi/rateYo#26]
rateYo works fine on "rtl: true" mode but when body direction set to rtl
```css
body{
   direction: rtl;
}
```
The element fails on shown. For solve that direction of div#rateYo must set to ltr. That appear rateYo doesn't work on rtl mode documentation.
